//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistAgency.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agencydbEntities1 : DbContext
    {
        public agencydbEntities1()
            : base("name=agencydbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Concert> Concert { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Musician> Musician { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
