//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistAgency.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int id { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public int idJob { get; set; }
        public Nullable<int> idActor { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Job Job { get; set; }
    }
}
